apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: journal-dragonfly-cache
spec:
  replicas: ${journal_cache_replicas:-1}
  args:
  - "--proactor_threads=2"
  - "--dbfilename=journal-cache-snapshot"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 640Mi
  snapshot:
    cron: "* * * * *"
    persistentVolumeClaimSpec:
      storageClassName: journal-gp3
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
