apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: journal-dragonfly-sessions
spec:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 192Mi
  snapshot:
    cron: "* * * * *"
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
