---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: articles
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
    konghq.com/plugins: key-auth, logging, cors, acl, vary-response-transformer, public-credentials-request-transformer-lax
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: ${lax_service_name}
      namespace: journal
      kind: Service
      port: ${lax_port}
    matches:
    - path:
        type: PathPrefix
        value: /articles
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /api/v2/articles
          type: ReplacePrefixMatch
