apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -api

resources:
# Journal CMS APIs
- labs-posts.yaml
- subjects.yaml
- podcast-episodes.yaml
- people.yaml
- blog-articles.yaml
- events.yaml
- interviews.yaml
- collections.yaml
- promotional-collections.yaml
- community.yaml
- covers.yaml
- press-packages.yaml
- job-adverts.yaml
- highlights.yaml
- annual-reports.yaml


- annotations.yaml
- recommendations.yaml
- digests.yaml

# - articles.yaml
# - bioprotocol.yaml

# - metrics.yaml
# - oauth2.yaml
# - profiles.yaml

# - search.yaml
