apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: api-raml-docs
spec:
  interval: 5m
  image: ghcr.io/elifesciences/api-raml-docs
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: api-raml-docs
spec:
  imageRepositoryRef:
    name: api-raml-docs
  policy:
    semver:
      range: '*'
