apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-raml-docs
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: api-raml-docs
        image: ghcr.io/elifesciences/api-raml-docs:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 3
