apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-raml-docs
resources:
- service.yaml
- deployment.yaml
- automations.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: api-gateway--${env}
    app.kubernetes.io/name: api-raml-docs
