apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: epp-client-stable
spec:
  imageRepositoryRef:
    name: epp-client
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>\d{8}\.\d{4})$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
