apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: journal-secrets
  namespace: journal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: journal-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: journal-team/journal/${env}
