apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: journal-secret-parameters
  namespace: journal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: journal-secret-parameters
    creationPolicy: Owner
    template:
      data:
        secret_parameters.yaml: |
          parameters:
            api_key: {{ .api_key | toString }}
            hypothesis_client_secret: {{ .hypothesis_client_secret | toString }}

            crm_api_key: {{ .crm_api_key | toString }}
            crm_api_site_key: {{ .crm_api_site_key | toString }}

            mailer_host: {{ .mailer_host | toString }}
            mailer_port: {{ .mailer_port | toString }}
            mailer_username: {{ .mailer_username | toString }}
            mailer_password: {{ .mailer_password | toString }}
            mailer_encryption: {{ .mailer_encryption | toString }}

            oauth2_client_secret: {{ .oauth2_client_secret | toString }}
            secret: {{ .secret | toString }}
  dataFrom:
  - extract:
      key: journal-team/journal/${env}
