apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: journal-parameters
  files:
  - config/parameters.yaml
  - config/era_articles.yaml
  - config/config_test.yaml
- name: nginx-journal-site-conf
  files:
  - config/nginx-site.conf
