apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iiif-cache-bucket
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/iiif/cache-bucket
  prune: true
  targetNamespace: journal--prod
  postBuild:
    substitute:
      # deployment vars
      env: prod
