apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cantaloupe
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/iiif/cantaloupe
  prune: true
  targetNamespace: journal--prod
  dependsOn:
  - name: iiif-cache-bucket
  - name: iiif-role
  images:
  - name: ghcr.io/elifesciences/cantaloupe
    newTag: 20250714061857.0.0-g6b3582d-16259499827-1-5.0.7 # {"$imagepolicy": "journal--prod:cantaloupe-stable:tag"}
  - name: ghcr.io/elifesciences/cantaloupe-caddy
    newTag: 20250714061857.0.0-g6b3582d-16259499827-1-v2.10.0 # {"$imagepolicy": "journal--prod:cantaloupe-caddy-stable:tag"}
  postBuild:
    substituteFrom:
    # iiif_cache_bucket_name is retrieved from the configmap
    - kind: ConfigMap
      name: iiif-cache-config
    # iiif_role_arn are retrieved from the configmap
    - kind: ConfigMap
      name: iiif-role
    substitute:
      env: prod
      hostname: iiif.prod.elifesciences.org
      replicas: "5"
      lax_prefix_url: 'https://s3-external-1.amazonaws.com/prod-elife-published/articles/'
      digests_prefix_url: 'https://s3-external-1.amazonaws.com/prod-elife-published/digests/'
      journal_cms_prefix_url: 'https://prod--journal-cms.elifesciences.org/sites/default/files/iiif/'
