apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iiif-role
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/iiif/aws-role
  prune: true
  targetNamespace: journal--prod
  dependsOn:
  - name: iiif-cache-bucket
  postBuild:
    substituteFrom:
      # iiif_cache_bucket_arn is retrieved from the configmap
      - kind: ConfigMap
        name: iiif-cache-config
    substitute:
      # deployment vars
      env: prod
      aws_oidc_arn: "${cluster_oidc_arn}"
      aws_oidc_url: "${cluster_oidc_url}"
      irsa_namespace: journal--prod
      iiif_epp_bucket_arn: arn:aws:s3:::prod-elife-epp-data
