---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: articles
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: ${lax_service_name}
      namespace: journal
      kind: Service
      port: ${lax_port}
    matches:
    - path:
        type: RegularExpression
        value: /articles(.*)
    # This isn't working due to the implementation using the reqiuest-transformer Kong plugin,
    # which is also used by public-credentials-request-transformer-lax, and  it's a highlander scenario
    # filters:
    # - type: URLRewrite
    #   urlRewrite:
    #     path:
    #       replacePrefixMatch: /api/v2/articles
    #       type: ReplacePrefixMatch
