apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: api-dummy
  namespace: journal--demo
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/api-dummy
  prune: true
  targetNamespace: journal--demo
  images:
    - name: ghcr.io/elifesciences/api-dummy
      newTag: 20241105162719.0.0-gdc9cb34-11688408106-1 # {"$imagepolicy": "journal--demo:api-dummy:tag"}
  postBuild:
    substitute:
      # deployment vars
      env: demo
