---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-dummy
  namespace: journal--demo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "api.demo.elifesciences.org"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-dummy
            port:
              number: 8080
  tls:
  - secretName: api-dummy-tls
    hosts:
    - "api.demo.elifesciences.org"
