apiVersion: v1
kind: Service
metadata:
  name: annotations
  namespace: journal
spec:
  type: ExternalName
  externalName: ${annotations_hostname}
  ports:
  - protocol: TCP
    port: ${annotations_port}
