apiVersion: v1
kind: Service
metadata:
  name: annotations
  namespace: journal
spec:
  type: ExternalName
  externalName: ${annotations_hostname}
  ports:
  - protocol: ${annotations_protocol}
    port: ${annotations_port}
