apiVersion: v1
kind: Service
metadata:
  name: bioprotocol
  namespace: journal
spec:
  type: ExternalName
  externalName: ${bioprotocol_hostname}
  ports:
  - protocol: ${bioprotocol_protocol}
    port: ${bioprotocol_port}
