apiVersion: v1
kind: Service
metadata:
  name: data-hub-metrics-api
  namespace: journal
  annotations:
    konghq.com/protocol: ${data_hub_metrics_api_protocol}
spec:
  type: ExternalName
  externalName: ${data_hub_metrics_api_hostname}
  ports:
  - protocol: TCP
    port: ${data_hub_metrics_api_port}
