apiVersion: v1
kind: Service
metadata:
  name: digests
  namespace: journal
spec:
  type: ExternalName
  externalName: ${digests_hostname}
  ports:
  - protocol: ${digests_protocol}
    port: ${digests_port}
