apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -proxy

resources:
  - annotations.yaml
  - bioprotocol.yaml
  - journal-cms.yaml
  - lax.yaml
  - metrics.yaml
  - profiles.yaml
  - reviewed-preprints.yaml
