apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: journal
spec:
  type: ExternalName
  externalName: ${metrics_hostname}
  ports:
  - protocol: ${metrics_protocol}
    port: ${metrics_port}
