apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: journal
  annotations:
    konghq.com/protocol: ${metrics_protocol}
spec:
  type: ExternalName
  externalName: ${metrics_hostname}
  ports:
  - protocol: TCP
    port: ${metrics_port}
