apiVersion: v1
kind: Service
metadata:
  name: profiles
  namespace: journal
spec:
  type: ExternalName
  externalName: ${profiles_hostname}
  ports:
  - protocol: ${profiles_protocol}
    port: ${profiles_port}
