apiVersion: v1
kind: Service
metadata:
  name: profiles
  namespace: journal
  annotations:
    konghq.com/protocol: ${profiles_protocol}
spec:
  type: ExternalName
  externalName: ${profiles_hostname}
  ports:
  - protocol: TCP
    port: ${profiles_port}
