apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: journal
spec:
  type: ExternalName
  externalName: ${recommendations_hostname}
  ports:
  - protocol: ${recommendations_protocol}
    port: ${recommendations_port}
