apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: journal
  annotations:
    konghq.com/protocol: ${recommendations_protocol}
spec:
  type: ExternalName
  externalName: ${recommendations_hostname}
  ports:
  - protocol: TCP
    port: ${recommendations_port}
