apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- import-job.yaml
- import-research-articles.yaml
- import-reviewed-preprints.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: queue
    app.kubernetes.io/name: queue-watcher
