apiVersion: batch/v1
kind: CronJob
metadata:
  name: search-queue-reindex
  namespace: journal
spec:
  suspend: true
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccount: search-queue-watcher
          containers:
          - name: search
            image: ghcr.io/elifesciences/search:latest
            command:
            - bash
            - "-c"
            - '/app/bin/reindex elife_search_$(date "+%Y%m%d%H%M%S")'
            resources:
              requests:
                memory: "4Gi"
                cpu: "600m"
              limits:
                memory: "4Gi"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config.php
              subPath: config.php
          volumes:
          - name: config-volume
            configMap:
              name: search-config
              items:
              - key: config.php
                path: config.php
