# This is used purely to redirect similar domains to the journal, with SSL
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Cache-Control "public, max-age=86400, immutable";
      return 302 https://elifesciences.org$request_uri;
  name: test-journal-redirects
  namespace: journal--prod
spec:
  rules:
  - host: test-redirect-1.elifesciences.net
  - host: test-redirect-2.elifesciences.net
  tls:
  - hosts:
    - test-redirect-1.elifesciences.net
    - test-redirect-2.elifesciences.net
    secretName: test-redirects-domain-tls
