---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digests
  namespace: journal
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: digests
        image: elifesciences/digests:23f3d932a3fce58d7660f93316479918d53faa52
        args:
        - bash
        - -c
        - "./migrate.sh && exec venv/bin/uwsgi --ini=/srv/digests/uwsgi.ini --enable-threads"
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "${DATABASE_URL}"
        - name: AWS_DEFAULT_REGION
          value: "${awsRegion}"
        - name: BUS_REGION
          value: "${busRegion}"
        - name: BUS_SUBSCRIBER
          value: "${busSubscriber}"
        - name: BUS_NAME
          value: "${busName}"
        - name: BUS_ENV
          value: "${busEnv}"
        # readinessProbe:
        #   exec:
        #     command:
        #       - bash
        #       - -c
        #       - "venv/bin/uwsgi_curl 127.0.0.1:9000 localhost/ping | grep pong"
        #   periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /srv/digests/uwsgi.ini
          subPath: uwsgi.ini
      volumes:
      - name: config-volume
        configMap:
          name: uwsgi-config
          items:
          - key: uwsgi.ini
            path: uwsgi.ini
