apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digests-api
  annotations:
    cert-manager.io/cluster-issuer: "${cert_manager_issuer}"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ${basic_auth_secret_name}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - eLife Digests API'
spec:
  rules:
  - host: ${hostname}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: digests-api
            port:
              number: 9000
  tls:
  - hosts:
    - ${hostname}
    secretName: ${hostname}-tls
