apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- digests.yaml
- serviceaccount.yaml
- service.yaml
- ingress.yaml
- automations/repository.yaml
- automations/stable-policy.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: digests
    app.kubernetes.io/instance: digests-${env}

configMapGenerator:
- name: digests-config
  files:
  - config/uwsgi.ini
  - config/json-parser.conf
