---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: search-queue-arn
spec:
  to:
    name: search-queue-config
    kind: configmap
    key: search_queue_arn
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: sqs.services.k8s.aws
      kind: Queue
      name: search-queue
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: search-queue-name
spec:
  to:
    name: search-queue-config
    kind: configmap
    key: search_queue_name
  from:
    path: ".spec.queueName"
    resource:
      group: sqs.services.k8s.aws
      kind: Queue
      name: search-queue
