apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: search-queue
spec:
  queueName: elife-search-${env}
  tags:
    Project: journal
  policy: |
    {
      "Version": "2008-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:${aws_accountid}:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_articles_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_podcast_episodes_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_collections_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_interviews_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_blog_articles_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_labs_posts_topic_arn}"
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "SQS:SendMessage",
          "Resource": "arn:aws:sqs:${aws_region}:512686554592:elife-search-${env}",
          "Condition": {
            "StringLike": {
              "aws:SourceArn": "${bus_reviewed_preprints_topic_arn}"
            }
          }
        }
      ]
    }
