apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: search-stable
spec:
  imageRepositoryRef:
    name: search
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
