apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libero-continuum-adaptor-auth-key
  namespace: journal
  labels:
    konghq.com/credential: key-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: libero-continuum-adaptor-auth-key
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: journal-team/api-gateway/consumers
      property: libero-continuum-adaptor
