---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: journal-cms
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: ${journal_cms_service_name}
      namespace: journal
      kind: Service
      port: ${journal_cms_port}
    matches:
    - path:
        type: PathPrefix
        value: /ping/journal-cms
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /ping
          type: ReplacePrefixMatch
