apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- annotations.yaml
- bioprotocol.yaml
- digests.yaml
- journal-cms.yaml
- lax.yaml
- metrics.yaml
- profiles.yaml
- recommendations.yaml
- search.yaml
- reviewed-preprints.yaml
