---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: journal
spec:
  general:
    serviceName: opensearch
    serviceAccount: opensearch
    version: 2.16.0
    monitoring:
      enable: false
    pluginsList:
    - "https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.16.0.0/prometheus-exporter-2.16.0.0.zip"
    - "repository-s3"
    snapshotRepositories:
    - name: ${aws_backup_s3_bucket}
      type: s3
      settings:
        bucket: ${aws_backup_s3_bucket}
        region: ${aws_region}
        base_path: journal/search/opensearch/${env}
    # This is to work around JRE permission issues, see https://github.com/opensearch-project/opensearch-k8s-operator/issues/442
    additionalVolumes:
    - name: aws-iam-token
      path: /usr/share/opensearch/config/aws-iam-token
  dashboards:
    version: 2.16.0
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "210m"
      limits:
        memory: "256Mi"
  nodePools:
  - component: managers
    replicas: 3
    additionalConfig:
      # This is to work around JRE permission issues, see https://github.com/opensearch-project/opensearch-k8s-operator/issues/442
      s3.client.default.identity_token_file: /usr/share/opensearch/config/aws-iam-token/token
    resources:
      requests:
        memory: "3840Mi"
        cpu: "100m"
      limits:
        memory: "3840Mi"
    roles:
    - "cluster_manager"
    diskSize: 5Gi
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          opster.io/opensearch-cluster: opensearch
          opster.io/opensearch-nodepool: managers
    pdb:
      enable: true
      maxUnavailable: 1
    persistence:
      pvc:
        storageClass: journal-gp3
        accessModes:
          - ReadWriteOnce
  - component: data
    replicas: 3
    additionalConfig:
      # This is to work around JRE permission issues, see https://github.com/opensearch-project/opensearch-k8s-operator/issues/442
      s3.client.default.identity_token_file: /usr/share/opensearch/config/aws-iam-token/token
    resources:
      requests:
        memory: "4Gi"
        cpu: "100m"
      limits:
        memory: "4Gi"
    roles:
    - "data"
    diskSize: 30Gi
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          opster.io/opensearch-cluster: opensearch
          opster.io/opensearch-nodepool: data
    pdb:
      enable: true
      maxUnavailable: 1
    persistence:
      pvc:
        storageClass: journal-gp3
        accessModes:
          - ReadWriteOnce
