apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- cluster.yaml
- serviceaccount.yaml
- servicemonitor.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/name: opensearch
