imports:
  - resource: secret_parameters.yml # see external secret
parameters:
    redis_cache: "redis://valkey-cache-master:6379"
    redis_sessions: "redis://valkey-sessions-master:6379"
    dismissible_info_bars: {}

    session_name: journal
    oauth2_client_id: journal--${env}
    trusted_hosts:
    - infra-ingress-nginx-controller.infra

    mailer_transport: smtp

    crm_url: https://crm.elifesciences.org/crm/civicrm/
    crm_api_url: https://crm.elifesciences.org/crm/sites/all/modules/civicrm/extern/rest.php

    api_url: test--gateway.elifesciences.org
    api_url_public: test--gateway.elifesciences.org

    google_api_client.config:
        client_id: '%env(GOOGLE_API_CLIENT_CLIENT_ID)'
        client_secret: '%env(GOOGLE_API_CLIENT_CLIENT_SECRET)'
    google_api_client.refresh_token: '%env(GOOGLE_API_CLIENT_REFRESH_TOKEN)'
    google_api_client.optout_unsubscribe_spreadsheet_id: '%env(GOOGLE_API_CLIENT_OPTOUT_UNSUBSCRIBE_SPREADSHEET_ID)'

    # defaults for URL generation - host
    router.request_context.host: ${hostname}

    # defaults for URL generation - scheme
    router.request_context.scheme: https
