apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bus-digests-topic
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/digests/bus-topic
  prune: true
  targetNamespace: journal--prod
  postBuild:
    substitute:
      env: journal--prod
