apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- opensearch
- web
- queue-import
- queue-watcher
- automation
- queue-serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: search
    app.kubernetes.io/instance: search-${env}

configMapGenerator:
- name: search-config
  files:
  - config/config.php
- name: search-log-config
  files:
  - config/json-parser.conf
