---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey-sessions
spec:
  interval: 5m
  chart:
    spec:
      chart: valkey
      version: "0.3.17"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    architecture: standalone
    auth:
      enabled: false
