---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey-cache
spec:
  interval: 5m
  chart:
    spec:
      chart: valkey
      version: "v0.0.24"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    architecture: standalone
    auth:
      enabled: false
