---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: journal-valkey-sessions
spec:
  interval: 5m
  chart:
    spec:
      chart: valkey
      version: "3.0.22"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    global:
      defaultStorageClass: journal-gp3
      security:
        allowInsecureImages: true
    image:
      repository: bitnamilegacy/valkey
      tag: 8.1.3-debian-12-r1
    architecture: standalone
    auth:
      enabled: false
    primary:
      resourcesPreset: none
      resources:
        limits:
          ephemeral-storage: 2Gi
          memory: 192Mi
        requests:
          cpu: 100m
          ephemeral-storage: 50Mi
          memory: 128Mi
