apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- automations.yaml
- deployment.yaml
- serviceaccount.yaml
- service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: continuum
    app.kubernetes.io/name: journal-downloads
    app.kubernetes.io/component: journal-downloads
    app.kubernetes.io/instance: ${instance_name:-journal-downloads}-${env}
