apiVersion: v1
kind: Service
metadata:
  name: journal-downloads-web
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
