apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- deployment.yaml
- service.yaml
- config/recommendations-ingress-fastcgi-params.yaml
- ingress.yaml

configMapGenerator:
- name: recommendations-config
  files:
  - config/config.php

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: recommendations
    app.kubernetes.io/instance: recommendations-${env}
