apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- deployment.yaml
- service.yaml
- config/recommendations-ingress-fastcgi-params.yaml
- automations/repository.yaml
- automations/stable-policy.yaml

configMapGenerator:
- name: recommendations-config
  files:
  - config/config.php
  - config/json-parser.conf
  - config/php-fpm-www-tweaks.conf
- name: nginx-recommendations-site-conf
  files:
  - config/nginx-site.conf

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: recommendations
    app.kubernetes.io/instance: recommendations-${env}
