apiVersion: v1
kind: Service
metadata:
  name: recommendations-fastcgi
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
