apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: search
  namespace: journal--filter-by-term
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/search/app
  prune: true
  targetNamespace: journal--filter-by-term
  images:
    - name: ghcr.io/elifesciences/search
      newTag: filter-by-term-multi-4decd237-20250201
  dependsOn:
  - name: search-queue
  - name: search-queue-watcher-role
  postBuild:
    substituteFrom:
    # search_queue_arn and search_queue_name are retrieved from the configmap
    - kind: ConfigMap
      name: search-queue-config
    # search_queue_watcher_role_arn are retrieved from the configmap
    - kind: ConfigMap
      name: search-queue-watcher-role
    substitute:
      # opensearch resources
      opensearch_manager_request_mem: 2938Mi
      opensearch_manager_request_cpu: 100m
      opensearch_manager_limit_mem: 2938Mi
      opensearch_data_request_mem: 5102Mi
      opensearch_data_request_cpu: 3500m
      opensearch_data_limit_mem: 5102Mi

      # opensearch backup vars
      aws_region: ${aws_region}
      aws_backup_s3_bucket: ${aws_backup_s3_bucket}
      aws_backup_service_account_role_arn: ${aws_backup_service_account_role_arn}

      # deployment vars
      env: filter-by-term
      hostname: search.filter-by-term.elifesciences.org
      cert_manager_issuer: "letsencrypt"

      api_url: https://api.prod.elifesciences.org
