apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: search-queue-watcher-role
  namespace: journal--filter-by-term
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/search/queue-watcher-role
  prune: true
  targetNamespace: journal--filter-by-term
  dependsOn:
  - name: search-queue
  postBuild:
    substituteFrom:
    # search_queue_arn and search_queue_name are retrieved from the configmap
    - kind: ConfigMap
      name: search-queue-config
    substitute:
      # deployment vars
      env: filter-by-term
      aws_oidc_arn: "${cluster_oidc_arn}"
      aws_oidc_url: "${cluster_oidc_url}"
      irsa_namespace: journal--filter-by-term
