apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: Distribution
metadata:
  name: redirects
  namespace: journal--prod
spec:
  distributionConfig:
    aliases:
      items:
      - "elifesciences.net"
      - "e-lifesciences.org"
      - "e-lifesciences.net"
      - "elifejournal.net"
      - "e-lifejournal.org"
      - "e-lifejournal.com"
      - "e-lifejournal.net"
      - "elifejournal.org"
    comment: string
    continuousDeploymentPolicyID: string
    customErrorResponses:
      items:
      - errorCachingMinTTL: integer
        errorCode: integer
        responseCode: string
        responsePagePath: string
    defaultCacheBehavior:
      allowedMethods:
        items:
        - "DELETE"
        - "GET"
        - "HEAD"
        - "OPTIONS"
        - "PATCH"
        - "POST"
        - "PUT"
        cachedMethods:
          items:
          - "GET"
          - "HEAD"
      compress: true
      defaultTTL: 0
      forwardedValues:
        cookies:
          forward: none
        headers:
          items:
          - Host
        queryString: true
      targetOriginID: redirects
      viewerProtocolPolicy: redirect-to-https
    enabled: true
    httpVersion: http2
    origins:
      items:
      - id: redirects
        domainName: redirects.prod.elifesciences.org
    viewerCertificate:
      acmCertificateARN: arn:aws:acm:us-east-1:512686554592:certificate/7ecad4de-174b-4f54-b52e-f0166e8001ab
      sslSupportMethod: sni-only
  tags:
  - key: Project
    value: journal
