apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: journal--staging
username: journal--staging
credentials:
- journal--staging-auth-key
- view-restricted-annotations-acl
- view-restricted-profiles-acl
- view-unpublished-content-acl
