---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digests
  namespace: journal
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: digests
        image: elifesciences/digests:23f3d932a3fce58d7660f93316479918d53faa52
        ports:
        - containerPort: 9000
        # readinessProbe:
        #   exec:
        #     command:
        #       - bash
        #       - -c
        #       - "venv/bin/uwsgi_curl 127.0.0.1:9000 localhost/ping | grep pong"
        #   periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /srv/digests/uwsgi.ini
          subPath: uwsgi.ini
      volumes:
      - name: config-volume
        configMap:
          name: uwsgi-config
          items:
          - key: uwsgi.ini
            path: uwsgi.ini
