apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- digests.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: digests
    app.kubernetes.io/instance: digests-${env}
