apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- web

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: search
    app.kubernetes.io/instance: search-${env}
