{
 "title": "Journal Prod Health Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Saturation CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"journal-app-prod-public.*\", namespace=\"journal--prod\", container=\"journal\", cpu=\"total\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{exported_service=\"journal-prod-journal-app-prod-public-80@kubernetes\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{exported_service=\"journal-prod-journal-app-prod-public-80@kubernetes\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{exported_service=\"journal-prod-journal-app-prod-public-80@kubernetes\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{exported_service=\"journal-prod-journal-app-prod-public-80@kubernetes\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Rate by HTTP Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_service_requests_total{exported_service=\"journal-prod-journal-app-prod-public-80@kubernetes\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}