apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-queue-watcher
  namespace: journal
spec:
  template:
    spec:
      serviceAccount: search-queue-watcher
      containers:
      - name: search
        image: ghcr.io/elifesciences/search:latest
        command: ["bin/console", "queue:watch"]
        resources:
          requests:
            memory: "250Mi"
            cpu: "150m"
          limits:
            memory: "250Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.php
          subPath: config.php
        - name: logs
          mountPath: /app/var/logs
      - name: logs
        image: cr.fluentbit.io/fluent/fluent-bit
        command: ["/fluent-bit/bin/fluent-bit", "-i", "tail", "-p", "path=/app/var/logs/all.json", "-p", "parser=json", "-o", "stdout", "-p", "format=json_stream"]
        volumeMounts:
        - name: logs
          mountPath: /app/var/logs
      volumes:
      - name: logs
        emptyDir: {}
      - name: config-volume
        configMap:
          name: search-config
          items:
          - key: config.php
            path: config.php
