apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-queue-watcher
  namespace: journal
spec:
  template:
    spec:
      serviceAccount: search-queue-watcher
      containers:
      - name: search
        image: ghcr.io/elifesciences/search:latest
        command: ["bin/console", "queue:watch"]
        resources:
          requests:
            memory: "250Mi"
            cpu: "150m"
          limits:
            memory: "250Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.php
          subPath: config.php
        - name: logs
          mountPath: /app/var/logs
      - name: logs
        image: cr.fluentbit.io/fluent/fluent-bit
        command:
        - "/fluent-bit/bin/fluent-bit"
        - "--parser=/config/json-parser.conf"
        - "--input=tail"
        - "--prop=path=/app/var/logs/all.json"
        - "--prop=parser=search"
        - "--output=stdout"
        - "--prop=format=json_lines"
        volumeMounts:
        - name: logs
          mountPath: /app/var/logs
        - name: log-config-volume
          mountPath: /config/json-parser.conf
          subPath: json-parser.conf
      volumes:
      - name: logs
        emptyDir: {}
      - name: config-volume
        configMap:
          name: search-config
          items:
          - key: config.php
            path: config.php
      - name: log-config-volume
        configMap:
          name: search-log-config
          items:
          - key: json-parser.conf
            path: json-parser.conf
