apiVersion: batch/v1
kind: CronJob
metadata:
  name: search-queue-import-rpp
  namespace: journal
spec:
  schedule: "0 7-18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccount: search-queue-watcher
          containers:
          - name: search
            image: ghcr.io/elifesciences/search:latest
            command:
            - bash
            - "-c"
            - '/app/bin/console queue:import ReviewedPreprints --dateFrom="$(date -d "7 days ago" +"%Y-%m-%dT00:00:00Z")"'
            resources:
              requests:
                memory: "4Gi"
                cpu: "600m"
              limits:
                memory: "4Gi"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config.php
              subPath: config.php
          volumes:
          - name: config-volume
            configMap:
              name: search-config
              items:
              - key: config.php
                path: config.php
