
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: search-queue-watcher-scaledobject
  namespace: journal
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  scaleTargetRef:
    name: search-queue-watcher
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: search-queue-watcher-scaledobject
    metadata:
      awsRegion: "${aws_region}"
      queueURL: "${search_queue_name}"
      queueLength: "50"
