apiVersion: apps/v1
kind: Deployment
metadata:
  name: cantaloupe
spec:
  replicas: ${replicas:=1}
  strategy:
    rollingUpdate:
      maxUnavailable: ${maxUnavailable:=25%}
  template:
    spec:
      serviceAccount: iiif
      containers:
        - name: cantaloupe
          image: ghcr.io/elifesciences/cantaloupe:latest
          env:
            - name: SOURCE_DELEGATE
              value: "true"
            - name: DELEGATE_SCRIPT_ENABLED
              value: "true"
            - name: DELEGATE_SCRIPT_PATHNAME
              value: /delegate/journal_delegate.rb
            - name: HTTPSOURCE_LOOKUP_STRATEGY
              value: ScriptLookupStrategy
            - name: PROCESSOR_DOWNSCALE_LINEAR
              value: "false"
            - name: PROCESSOR_BACKGROUND_COLOR
              value: white
            - name: PRINT_STACK_TRACE_ON_ERROR_PAGES
              value: "false"
            - name: CACHE_SERVER_DERIVATIVE_ENABLED
              value: "true"
            - name: CACHE_SERVER_DERIVATIVE
              value: "S3Cache"
            - name: S3Cache.region
              value: "us-east-1"
            - name: S3CACHE_BUCKET_NAME
              value: "${iiif_cache_bucket_name}"
            - name: S3CACHE_OBJECT_KEY_PREFIX
              value: "iiif-cache/"
            # - name: PROCESSOR_JPG_QUALITY
            #   value: "100"
          # resources:
          #   requests:
          #     cpu: 1000m
          #     memory: 1Gi
          #   limits:
          #     memory: 1.5Gi
          ports:
            - name: http
              containerPort: 8182
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: iiif-journal-delegate-volume
              mountPath: /delegate/journal_delegate.rb
              subPath: journal_delegate.rb
      volumes:
        - name: iiif-journal-delegate-volume
          configMap:
            name: iiif-journal-delegate
            items:
            - key: journal_delegate.rb
              path: journal_delegate.rb
