apiVersion: apps/v1
kind: Deployment
metadata:
  name: cantaloupe
spec:
  replicas: ${replicas:=1}
  strategy:
    rollingUpdate:
      maxUnavailable: ${maxUnavailable:=25%}
  template:
    spec:
      serviceAccount: iiif
      containers:
        - name: cantaloupe
          image: ghcr.io/elifesciences/cantaloupe:latest
          env:
            - name: SOURCE_DELEGATE
              value: "true"
            - name: DELEGATE_SCRIPT_ENABLED
              value: "true"
            - name: DELEGATE_SCRIPT_PATHNAME
              value: /delegate/journal_delegate.rb
            - name: HTTPSOURCE_LOOKUP_STRATEGY
              value: ScriptLookupStrategy
            - name: PROCESSOR_DOWNSCALE_LINEAR
              value: "false"
            - name: PROCESSOR_BACKGROUND_COLOR
              value: white
            - name: PRINT_STACK_TRACE_ON_ERROR_PAGES
              value: "false"
            - name: CACHE_SERVER_DERIVATIVE_ENABLED
              value: "true"
            - name: CACHE_SERVER_DERIVATIVE
              value: "S3Cache"
            - name: S3CACHE_REGION
              value: "us-east-1"
            - name: S3CACHE_BUCKET_NAME
              value: "${iiif_cache_bucket_name}"
            - name: S3CACHE_OBJECT_KEY_PREFIX
              value: "iiif-cache/"
            - name: MAX_PIXELS
              value: "256000000"
            - name: MAX_SCALE
              value: "2.0"
              # configure max heap size
            - name: JAVA_OPTS
              value: "-Xmx2560m"
            # - name: PROCESSOR_JPG_QUALITY
            #   value: "100"
          resources:
            requests:
              cpu: 600m
              memory: 3Gi
          ports:
            - name: cantaloupe
              containerPort: 8182
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: cantaloupe
          readinessProbe:
            tcpSocket:
              port: cantaloupe
          volumeMounts:
            - name: iiif-journal-delegate-volume
              mountPath: /delegate/journal_delegate.rb
              subPath: journal_delegate.rb
        - name: caddy
          image: ghcr.io/elifesciences/cantaloupe-caddy:latest
          ports:
            - name: iiif-journal
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: caddy-proxy-config-volume
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: iiif-journal-delegate-volume
          configMap:
            name: iiif-journal-delegate
            items:
            - key: journal_delegate.rb
              path: journal_delegate.rb
        - name: caddy-proxy-config-volume
          configMap:
            name: caddy-proxy-config
            items:
            - key: Caddyfile
              path: Caddyfile
