apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- serviceaccount.yaml
- automations

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: iiif
    app.kubernetes.io/instance: iiif--${env}
    app.kubernetes.io/name: cantaloupe

configMapGenerator:
- name: iiif-journal-delegate
  files:
  - config/journal_delegate.rb
- name: caddy-proxy-config
  files:
  - config/Caddyfile
- name: loris-config
  files:
  - lorisconfig/wsgi.ini
