apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: iiif
  namespace: journal
spec:
  name: elife-iiif-${env}
  tags:
  - key: Project
    value: journal
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "${aws_oidc_arn}"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "ForAnyValue:StringEquals": {
              "${aws_oidc_url}:sub": [
                "system:serviceaccount:${irsa_namespace}:iiif-${env}"
              ]
            }
          }
        }
      ]
    }
