apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- deployment.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: web
