apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: iiif
    app.kubernetes.io/instance: iiif--${env}
    app.kubernetes.io/name: loris

configMapGenerator:
- name: loris-config
  files:
  - config/uwsgi.ini
