apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api-dummy
spec:
  interval: 5m
  image: ghcr.io/elifesciences/api-dummy
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-dummy
spec:
  imageRepositoryRef:
    name: api-dummy
  policy:
    semver:
      range: '*'
