apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: api-dummy
spec:
  interval: 5m
  image: ghcr.io/elifesciences/api-dummy
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: api-dummy
spec:
  imageRepositoryRef:
    name: api-dummy
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+).*'
    extract: '$semver'
  policy:
    semver:
      range: '*'
