apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-dummy
resources:
- service.yaml
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: api-dummy
    app.kubernetes.io/instance: api-dummy--${env}
    app.kubernetes.io/name: api-dummy
