apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: journal-preview
spec:
  imageRepositoryRef:
    name: journal
  filterTags:
    pattern: '^preview-1954-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
