---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: annotations
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: ${annotations_service_name}
      namespace: journal
      kind: Service
      port: ${annotations_port}
    matches:
    - path:
        type: PathPrefix
        value: /annotations
