---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: data-hub-metrics
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
    konghq.com/rewrite: '/elife-metrics/$1'
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: ${data_hub_metrics_api_service_name}
      namespace: ${data_hub_metrics_api_namespace}
      kind: Service
      port: ${data_hub_metrics_api_port}
    matches:
    - path:
        type: RegularExpression
        value: "/metrics/(article/[0-9]+/citations/version/[0-9]+)"
