apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  konghq.com/plugins: key-auth, logging, cors, acl, vary-response-transformer
resources:
- annotations.yaml
- recommendations.yaml
- digests.yaml
- bioprotocol.yaml
- search.yaml
- oauth2.yaml

- metrics.yaml
- reviewed-preprints.yaml
- data-hub-metrics-api.yaml
