---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-cms
  namespace: journal
spec:
  replicas: ${replicas:-1}
  template:
    spec:
      serviceAccountName: journal-cms
      containers:
      - name: journal-cms
        image: ghcr.io/elifesciences/journal-cms:latest
        ports:
        - containerPort: 8080
        env:
        - name: DRUPAL_DATABASE_NAME
          value: ${journal_cms_database_name}
        - name: DRUPAL_DATABASE_USERNAME
          value: ${journal_cms_database_username}
        - name: DRUPAL_DATABASE_HOST
          value: ${journal_cms_database_host}
        - name: DRUPAL_DATABASE_PORT
          value: ${journal_cms_database_port:-\"3306\"}
        - name: DRUPAL_DATABASE_PASSWORD
          value: ${journal_cms_database_password}
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_database_password_secret_name}
              key: ${journal_cms_database_password_secret_key}

        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: journal-cms-files
          mountPath: /opt/drupal/web/sites/default/files/
      volumes:
      - name: journal-cms-files
        persistentVolumeClaim:
          claimName: journal-cms-files
