---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-cms-app
  namespace: journal
spec:
  replicas: ${replicas:-1}
  template:
    spec:
      serviceAccountName: journal-cms
      initContainers:
      - name: update-db
        image: ghcr.io/elifesciences/journal-cms:latest
        command: [ "drush", "updatedb", "-y" ]
        envFrom:
        # General Drupal config
        - configMapRef:
            name: journal-cms-app-config
        env:
        # Drupal security config
        - name: DRUPAL_HASH_SALT
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_app_hash_salt_secret_name}
              key: ${journal_cms_app_hash_salt_secret_key}
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_database_password_secret_name}
              key: ${journal_cms_database_password_secret_key}
      - name: config-import
        image: ghcr.io/elifesciences/journal-cms:latest
        command: [ "drush", "config-import", "-y" ]
        envFrom:
        # General Drupal config
        - configMapRef:
            name: journal-cms-app-config
        env:
        # Drupal security config
        - name: DRUPAL_HASH_SALT
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_app_hash_salt_secret_name}
              key: ${journal_cms_app_hash_salt_secret_key}
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_database_password_secret_name}
              key: ${journal_cms_database_password_secret_key}
      containers:
      - name: journal-cms
        image: ghcr.io/elifesciences/journal-cms:latest
        ports:
        - containerPort: 8080
        envFrom:
        # General Drupal config
        - configMapRef:
            name: journal-cms-app-config
        env:
        # Drupal security config
        - name: DRUPAL_HASH_SALT
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_app_hash_salt_secret_name}
              key: ${journal_cms_app_hash_salt_secret_key}
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${journal_cms_database_password_secret_name}
              key: ${journal_cms_database_password_secret_key}
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: journal-cms-files
          mountPath: /opt/drupal/web/sites/default/files/
      volumes:
      - name: journal-cms-files
        persistentVolumeClaim:
          claimName: journal-cms-files
