apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: continuum
    app.kubernetes.io/component: journal-cms
    app.kubernetes.io/name: journal-cms-app
    app.kubernetes.io/instance: ${instance_name:-journal-cms-app}-${env}
