apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- journal

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: continuum
    app.kubernetes.io/name: journal
    app.kubernetes.io/instance: ${instance_name:-journal}-${env}
