apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- valkey
- journal

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: journal
    app.kubernetes.io/instance: journal-${env}
