apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: journal
  namespace: journal--demo
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/journal
  prune: true
  targetNamespace: journal--demo
  images:
    - name: ghcr.io/elifesciences/journal # {"$imagepolicy": "journal--demo:journal-stable:name"}
      newTag: master-abb6821bcb98315a58ac41542a9f4ec3a2b41051-20241206.1129 # {"$imagepolicy": "journal--demo:journal-stable:tag"}
  postBuild:
    substitute:
      # deployment vars
      env: demo
      hostname: journal.demo.elifesciences.org
      cert_manager_issuer: "letsencrypt"
      journal_secret_parameters_secret_name: journal-secret-parameters
      api_url: https://api.demo.elifesciences.org/
      api_url_search_page: https://api.demo.elifesciences.org
      epp_url: http://epp-client.epp--prod:3000
      observer_url: http://prod--observer.elife.internal
      pubpub_url: https://elife-container.pubpub.org
      hubspot_url: https://connect.elifesciences.org
