---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: root-documentation-redirect
  namespace: journal
  annotations:
    konghq.com/preserve-host: "false"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: journal
  rules:
  - backendRefs:
    - name: api-raml-docs
      namespace: journal
      kind: Service
      port: 80
    matches:
    - path:
        type: Exact
        value: /
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /documentation/
