apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: journal-cms-unpublished-content-auth-key
  namespace: journal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: journal-cms-unpublished-content-auth-key
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: journal-team/api-gateway/consumers
      property: journal-cms-unpublished-content
