---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-articles
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_articles_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-podcast-episodes
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_podcast_episodes_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-collections
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_collections_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-interviews
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_interviews_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-blog-articles
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_blog_articles_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-labs-posts
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_labs_posts_topic_arn}
  tags:
    Project: journal
---
apiVersion: sns.services.k8s.aws/v1alpha1
kind: Subscription
metadata:
  name: search-queue-subscription-bus-reviewed-preprints
spec:
  endpoint: ${search_queue_arn}
  protocol: sqs
  topicARN: ${bus_reviewed_preprints_topic_arn}
  tags:
    Project: journal
