apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: journal--prod-auth-key
  namespace: journal
  labels:
    konghq.com/credential: key-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: journal--prod-auth-key
    creationPolicy: Merge
  data:
  - secretKey: key
    remoteRef:
      key: journal-team/api-gateway/consumers
      property: journal--prod
