apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: search-queue-watcher
  namespace: journal
spec:
  name: search--${env}-queue-watcher
  tags:
  - key: Project
    value: journal
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "${aws_oidc_arn}"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "ForAnyValue:StringEquals": {
              "${aws_oidc_url}:sub": [
                "system:serviceaccount:${irsa_namespace}:search-queue-watcher"
              ]
            }
          }
        },
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "${aws_oidc_arn}"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "ForAnyValue:StringEquals": {
              "${aws_oidc_url}:sub": [
                "system:serviceaccount:${keda_namespace}:${keda_service_account_name}"
              ]
            }
          }
        }
      ]
    }
  inlinePolicies:
    all-sqs-permissions-to-queue: |
      {
        "Version": "2012-10-17",
        "Statement": [{
            "Effect": "Allow",
            "Action": "*",
            "Resource": "${search_queue_arn}"
        }]
      }
