---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: search-queue-watcher-role-arn
spec:
  to:
    name: search-queue-watcher-role
    kind: configmap
    key: search_queue_watcher_role_arn
  from:
    path: ".status.ackResourceMetadata.arn"
    resource:
      group: iam.services.k8s.aws
      kind: Role
      name: search-queue-watcher
