apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  interval: 5m
  image: ghcr.io/elifesciences/api-dummy
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  imageRepositoryRef:
    name: api-dummy
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+).*'
    extract: '$semver'
  policy:
    semver:
      range: '*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  update:
    strategy: Setters
    path: ./manifests/previews/journal-api-dummy
  git:
    commit:
      author:
        name: Fluxbot
        email: flux@elifesciences.org
      messageTemplate: |
        release({{ .AutomationObject }}): Automatic release

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
