apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  interval: 5m
  image: ghcr.io/elifesciences/api-dummy
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  imageRepositoryRef:
    name: api-dummy
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+).*'
    extract: '$semver'
  policy:
    semver:
      range: '*'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: api-dummy
  namespace: journal--previews
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  update:
    strategy: Setters
    path: ./manifests/previews/journal-api-dummy
  git:
    commit:
      author:
        name: Fluxbot
        email: flux@elifesciences.org
      messageTemplate: |
        deploy({{ .AutomationObject }}): Automatic deploy

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Namespace }}/{{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
          - {{ $change.Setter }}: {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
