apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: journal-api-dummy
  namespace: journal--previews
spec:
  serviceAccountName: journal-previews
  prune: true
  matrix:
  - name: pr
    object:
      ref:
        apiVersion: templates.kluctl.io/v1alpha1
        kind: ListGithubPullRequests
        name: journal-api-dummy
      jsonPath: status.pullRequests
      expandLists: true
  templates:
  - object:
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImagePolicy
      metadata:
        name: journal-api-dummy-preview-{{ matrix.pr.number }}
        namespace: journal--previews
      spec:
        imageRepositoryRef:
          name: journal
        filterTags:
          pattern: '^preview-{{ matrix.pr.number }}-[a-fA-F0-9]+-(?P<ts>.*)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
  - object:
      apiVersion: templates.kluctl.io/v1alpha1
      kind: ObjectTemplate
      metadata:
        name: journal-api-dummy-preview-{{ matrix.pr.number }}
        namespace: journal--previews
      spec:
        serviceAccountName: journal-previews
        prune: true
        matrix:
        - name: image
          object:
            ref:
              apiVersion: image.toolkit.fluxcd.io/v1beta2
              kind: ImagePolicy
              name: journal-api-dummy-preview-{{ matrix.pr.number }}
            jsonPath: status.latestImage
        templates:
        - object:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: "journal--preview-{{ matrix.pr.number }}"
              annotations:
                elifesciences.org/default-project: journal
        - object:
            apiVersion: kustomize.toolkit.fluxcd.io/v1
            kind: Kustomization
            metadata:
              name: api-dummy--preview-{{ matrix.pr.number }}
              namespace: journal--previews
            spec:
              interval: 1m0s
              sourceRef:
                kind: GitRepository
                name: journal-team-deployment
                namespace: flux-system
              path: ./kustomizations/api-dummy
              prune: true
              targetNamespace: journal--preview-{{ matrix.pr.number }}
              images:
              - name: ghcr.io/elifesciences/api-dummy
                newTag: 20241105171536.0.0-g5834c98-11689211250-1 # {"$imagepolicy": "journal--previews:api-dummy:tag"}
              postBuild:
                substitute:
                  env: demo
        - object:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: journal-secret-parameters
              namespace: "journal--preview-{{ matrix.pr.number }}"
            spec:
              refreshInterval: 1h
              secretStoreRef:
                name: secret-store
                kind: ClusterSecretStore
              target:
                name: journal-secret-parameters
                creationPolicy: Owner
                template:
                  data:
                    secret_parameters.yaml: |
                      {% raw %}
                      parameters:
                        api_key: {{ '{{ .api_key | toString }}' }}
                        hypothesis_client_secret: {{ '{{ .hypothesis_client_secret | toString }}' }}

                        crm_api_key: {{ '{{ .crm_api_key | toString }}' }}
                        crm_api_site_key: {{ '{{ .crm_api_site_key | toString }}' }}

                        xpub_client_secret:  {{ '{{ .xpub_client_secret | toString }}' }}

                        mailer_host: {{ '{{ .mailer_host | toString }}' }}
                        mailer_port: {{ '{{ .mailer_port | toString }}' }}
                        mailer_username: {{ '{{ .mailer_username | toString }}' }}
                        mailer_password: {{ '{{ .mailer_password | toString }}' }}
                        mailer_encryption: {{ '{{ .mailer_encryption | toString }}' }}

                        oauth2_client_secret: {{ '{{ .oauth2_client_secret | toString }}' }}
                        secret: {{ '{{ .secret | toString }}' }}
                      {% endraw %}
              dataFrom:
              - extract:
                  key: journal-team/journal/demo
