---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cantaloupe
spec:
  interval: 5m
  image: ghcr.io/elifesciences/cantaloupe
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cantaloupe-stable
spec:
  imageRepositoryRef:
    name: cantaloupe
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+).*'
    extract: '$semver'
  policy:
    semver:
      range: '*'
