apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: journal-downloads-role
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/journal/downloads-role
  prune: true
  targetNamespace: journal--prod
  postBuild:
    substitute:
      # deployment vars
      env: prod
      aws_oidc_arn: "${cluster_oidc_arn}"
      aws_oidc_url: "${cluster_oidc_url}"
      irsa_namespace: journal--prod
