apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: journal-app-prod
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/journal
  prune: true
  targetNamespace: journal--prod
  images:
    - name: ghcr.io/elifesciences/journal # {"$imagepolicy": "journal--prod:journal-app-latest-master:name"}
      newTag: master-fedc16a8e12ef8a95512d0fef3307623762fecf2-20260728.1417 # {"$imagepolicy": "journal--prod:journal-app-latest-master:tag"}
  nameSuffix: -prod-public
  patches:
    - patch: |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: journal-app
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: journal-prod-journal-app-ip-allowlist@kubernetescrd
      target:
        kind: Ingress
        name: journal-app
  postBuild:
    substitute:
      # deployment vars
      env: prod
      instance_name: journal-app-prod
      hostname: journal-prod.test.elifesciences.org
      cert_manager_issuer: "letsencrypt"
      journal_secret_parameters_secret_name: journal-prod-secret-parameters
      api_url: https://api.prod.elifesciences.org
      api_url_search_page: https://api.prod.elifesciences.org
      epp_url: http://epp-client.epp--prod:3000
      observer_url: http://prod--observer.elife.internal
      pubpub_url: https://elife-container.pubpub.org
      hubspot_url: https://connect.elifesciences.org
      cache_uri: redis://prod-journal-dragonfly-cache:6379
      session_uri: redis://prod-journal-dragonfly-sessions:6379
