apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- gatewayconfiguration.yaml
- gatewayclass.yaml
- gateway.yaml
- plugins
- routes
- consumers
- acl-groups
# consumer keys should be deployed before this kustomization, otherwise kong gets upset about validation. see https://github.com/Kong/kubernetes-ingress-controller/issues/6480
# - consumers-keys

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: api-gateway
    app.kubernetes.io/instance: api-gateway-${env}
configurations:
- namespaceconfig.yaml
