apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal

resources:
- fallback-gateway.yaml
- ingress.yaml
- search.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: api-gateway
    app.kubernetes.io/instance: api-gateway-${env}
