apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: public-credentials-lax
  namespace: journal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: public-credentials-lax
    creationPolicy: Owner
    template:
      data:
        credentials: "{{ .lax_backend_credentials | toString }}"
        authorization-header: "Authorization: Basic {{ (print \"api-gateway:\" (.lax_backend_credentials | toString)) | b64enc }}"
        request-transformer-config: |
          add:
            headers:
            - "Authorization: Basic {{ (print "api-gateway:" (.lax_backend_credentials | toString)) | b64enc }}"
            - "X-Test: testvalue"
  dataFrom:
  - extract:
      key: journal-team/api-gateway/public-credentials
