apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: public-credentials-profiles
  namespace: journal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: public-credentials-profiles
    creationPolicy: Owner
    template:
      data:
        credentials: "{{ .profiles_backend_credentials | toString }}"
        authorization-header: "Authorization: Basic {{ (print \"api-gateway:\" (.profiles_backend_credentials | toString)) | b64enc }}"
        request-transformer-config: |
          append:
            headers:
            - "Authorization: Basic {{ (print "api_gateway:" (.profiles_backend_credentials | toString)) | b64enc }}"
  dataFrom:
  - extract:
      key: journal-team/api-gateway/public-credentials
