---
apiVersion: templates.kluctl.io/v1alpha1
kind: ListGithubPullRequests
metadata:
  name: journal--previews
  namespace: journal--previews
spec:
  interval: 1m
  owner: elifesciences
  repo: journal
  state: open
  base: master
  head: elifesciences:.*
  labels:
  - preview-prod-gateway
  limit: 100
