---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-elife-alfred-user-cluster-token
  namespace: journal--previews
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: github-elife-alfred-user-cluster-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: github/elife-alfred-user/cluster-token
