apiVersion: v1
kind: ServiceAccount
metadata:
  name: journal-previews
  namespace: journal--previews
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: journal-previews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: journal-previews
    namespace: journal--previews
