---
apiVersion: templates.kluctl.io/v1alpha1
kind: ListGithubPullRequests
metadata:
  name: journal-prod-gateway
  namespace: journal--previews
spec:
  interval: 1m
  owner: elifesciences
  repo: journal
  state: open
  base: develop
  head: elifesciences:.*
  labels:
  - preview-prod-gateway
  limit: 100
  tokenRef:
    secretName: github-elife-alfred-user-cluster-token
    key: token
