apiVersion: batch/v1
kind: CronJob
metadata:
  name: search-queue-import-all
  namespace: journal
spec:
  suspend: true
  schedule: "*/5 * * * *" # evey 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: journal-cms
          containers:
          - name: drupal-cron
            image: ghcr.io/elifesciences/journal-cms:latest
            command: [ "drush", "core-cron" ]
            envFrom:
            # General Drupal config
            - configMapRef:
                name: journal-cms-app-config
            env:
            # Drupal security config
            - name: DRUPAL_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: ${journal_cms_app_hash_salt_secret_name}
                  key: ${journal_cms_app_hash_salt_secret_key}
            - name: DRUPAL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${journal_cms_database_password_secret_name}
                  key: ${journal_cms_database_password_secret_key}
