apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif
spec:
  replicas: ${replicas:=1}
  strategy:
    rollingUpdate:
      maxUnavailable: ${maxUnavailable:=1}
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: cantaloupe
          image: ghcr.io/elifesciences/cantaloupe:latest
          env:
            - name: SOURCE_DELEGATE
              value: "true"
            - name: DELEGATE_SCRIPT_ENABLED
              value: "true"
            - name: DELEGATE_SCRIPT_PATHNAME
              value: /delegate/journal_delegate.rb
            - name: HTTPSOURCE_LOOKUP_STRATEGY
              value: ScriptLookupStrategy

            - name: PROCESSOR_DOWNSCALE_LINEAR
              value: "true"
            - name: PROCESSOR_JPG_QUALITY
              value: "100"
            - name: PROCESSOR_JPG_PROGRESSIVE
              value: "false"
            - name: PROCESSOR_IMAGEIO_TIF_READER
              value: "com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader"
            - name: PROCESSOR_SHARPEN
              value: "0.5"
          # resources:
          #   requests:
          #     cpu: 1000m
          #     memory: 1Gi
          #   limits:
          #     memory: 1.5Gi
          ports:
            - name: http
              containerPort: 8182
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: iiif-journal-delegate-volume
              mountPath: /delegate/journal_delegate.rb
              subPath: journal_delegate.rb
      volumes:
        - name: iiif-journal-delegate-volume
          configMap:
            name: iiif-journal-delegate
            items:
            - key: journal_delegate.rb
              path: journal_delegate.rb
