apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journal-app
  annotations:
    cert-manager.io/cluster-issuer: "${cert_manager_issuer}"
spec:
  ingressClassName: traefik
  rules:
  - host: ${hostname}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: journal-app
            port:
              number: 80
  tls:
  - hosts:
    - ${hostname}
    secretName: ${hostname}-tls
