apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: basex-validator
resources:
- automations.yaml
- service.yaml
- deployment.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: basex-validator
    app.kubernetes.io/instance: basex-validator--${env}
    app.kubernetes.io/name: basex-validator
